prplmesh: fix Python3 and YAML handling
prplMesh needs Python3 YAML module for automatic generation of TLVF
library. In prplOS we're using Python3 YAML module installed on the host
as implicit and mandatory build prerequisite.

That works fine unless there is python3/host OpenWrt package present on
the build system, in those cases CMake simply finds that interpreter
first and prplMesh fails to build as there is usually YAML module
missing:

 ModuleNotFoundError: No module named 'yaml.constructor'

So lets fix it by making the Python3 YAML module host dependency
explicit and assure usage of same Python3 interpreter in CMake as well.

Fixes: PCF-923
Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit d5592d503dfcbd9d9ac0ee2b17bf6526e3fe44b6)