prplMesh: pwhm: fix GCC11 compilation errors
While compiling pwhm with gcc version 11.2.0 which is used by default in
OpenWrt 22.03, we're getting following compile errors:

 wld_util.c:2031:37: error: argument 1 of type 'uint8_t[16]' {aka 'unsigned char[16]'} with mismatched bound [-Werror=array-parameter=]
 2031 | int makeUUID_fromMACaddress(uint8_t uuid[UUID_LEN], char MACaddr[18], int offset) { //ex:E8:F1:B0:CE:07:D4
      |                             ^~~~~~

See PPM-2363 (HOP-2995) for details.

Signed-off-by: Andrey Erokhin <a.erokhin@inango-systems.com>
Signed-off-by: Petr Štetiar <ynezz@true.cz> [PKG_RELEASE bump]
(cherry picked from commit 939cc906020318eeffd4e17094acc40b0fc199ba)