pwhm: add optional mac80211 dependency
SSW-8181 started to dynamically choose between
regular uapi linux/nl80211.h header and the one
provided by the mac80211 package that provides
backports.

This dependency was omitted in the pwhm Makefile
leading to unpredictable results. Typical
(undesired) outcomes were:

 a. linux/nl80211.h would be used instead of the
    mac80211/uapi/linux/nl80211.h

 b. mac80211/uapi/linux/nl80211.h would be used
    whilst mac80211 package is recompiled - causing
    a build error that looked like this:

> In file included from ../include/wld/wld_nl80211.h:71,
>                  from ../include/wld/wld_nl80211_attr.h:71,
>                  from ../include_priv/nl80211/wld_nl80211_api_priv.h:66,
>                  from nl80211/wld_nl80211_api.c:66:
> ../include/wld/wld_nl80211_path.h:1:10: fatal error: mac80211/uapi/linux/nl80211.h: No such file or directory
>     1 | #include <mac80211/uapi/linux/nl80211.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.

A simple way to reproduce (a) was to run the
following commands (this is against Banana Pi R4,
your mac80211 package path may vary):

> make package/feeds/feed_mediatek/mac80211/clean
> make package/feeds/feed_prplmesh/services/pwhm/clean
> make package/feeds/feed_prplmesh/services/pwhm/compile

Reproducing (b) was harder. It seems that it would
reproduce randomly for people when running massive
parallel builds with 32+ cores. I myself was
seeing (b) on 32c64t threadripper.

Relates-to: SSW-8181
References: PPW-779
Signed-off-by: Michal Kazior <michal@plume.com>